"""Base LLM interface."""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from typing import Callable, Optional, TypeVar

from app.schemas import RetrievedChunk

T = TypeVar("T")


def format_history(history: Optional[list[dict]] = None) -> str:
    """Render in-session memory as a short dialogue block for the LLM prompt.

    The memory is temporary (RAM, per session) and is deleted when the
    session ends; it never leaves the machine unless the backend is cloud.
    """
    if not history:
        return ""
    lines = ["Cuộc trò chuyện trước đó trong cùng phiên (người dân - tổng đài viên):"]
    for turn in history:
        if turn.get("user"):
            lines.append(f"[người dân]: {turn['user']}")
        if turn.get("assistant"):
            lines.append(f"[tổng đài viên]: {turn['assistant']}")
    return "\n".join(lines)


class LLMError(RuntimeError):
    """Raised when the LLM backend fails or returns unusable output."""


def retry_transient(
    fn: Callable[[], T],
    *,
    max_retries: int = 3,
    timeout_seconds: float = 60.0,
    backoff_seconds: float = 1.0,
    retryable: Callable[[Exception], bool] = lambda exc: True,
) -> T:
    """Call ``fn`` with exponential backoff on retryable exceptions.

    JSON/format errors are usually NOT retryable (they will fail the same
    way every time); network errors, 429 rate limits, and 5xx are.
    """
    attempt = 0
    while True:
        try:
            return fn()
        except Exception as exc:
            if attempt >= max_retries or not retryable(exc):
                raise
            attempt += 1
            time.sleep(backoff_seconds * (2 ** (attempt - 1)))


def _is_transient_http(error: Exception) -> bool:
    """True for network/timeout/429/5xx style errors from HTTP SDKs."""
    message = str(error).lower()
    if isinstance(error, (ConnectionError, TimeoutError, OSError)):
        return True
    return any(token in message for token in ("429", "500", "502", "503", "504", "timeout"))


def is_retryable_llm_error(error: Exception) -> bool:
    """Conservative retry policy: transient HTTP failures only."""
    return _is_transient_http(error)


class BaseLLM(ABC):
    """Interface for answer-generation backends.

    Contract:
    - Output is JSON with keys: answer_text, spoken_citation, limitations,
      next_step. source_ids are NOT generated by the LLM; the caller supplies
      the allowed set and enforces it (see :meth:`enforce_source_ids`).
    - No personal data beyond query text and provided chunks may be sent.
    """

    name: str = "base"

    @abstractmethod
    def generate_answer(
        self,
        query: str,
        chunks: list[RetrievedChunk],
        max_chars: int = 2000,
        history: Optional[list[dict]] = None,
    ) -> dict:
        """Return a JSON dict with answer fields.

        ``history`` carries the previous turns of the same session (temporary
        memory); backends may include it in the prompt, but answers must stay
        grounded on the ``chunks`` of the CURRENT turn.
        """

    def enforce_source_ids(self, parsed: dict, allowed: set[str]) -> dict:
        """Force source_ids from the answer to be a subset of allowed."""
        provided = parsed.get("source_ids") or []
        kept = [sid for sid in provided if sid in allowed]
        if kept != provided:
            parsed["source_ids"] = kept
            parsed["_source_ids_sanitized"] = True
        else:
            parsed["_source_ids_sanitized"] = False
        return parsed
